dotnet/dotnet-ci

nodes/startup/jenkins-osx-startup.plist, nodes/startup/jenkins-osx-startup.sh
To use:
* Change plist file credentials to appropriate ones for dotnet bot (API key).
* Change plist file to have correct path to startup script file.
* Copy plist file to ~/Library/LaunchAgents
* launchctl load ~/Library/LaunchAgents/jenkins-osx-startup.ps1
=> Add OSX startup scripts.

nodes/startup/jenkins-windows-startup.ps1
This prevents jenkins from killing processes on Windows.
=> Fix issue where a reconnected node won't load winp

jobs/dotnet_corefx_coverage_windows/config.xml, jobs/dotnet_corefx_linux_debug_tst_prtest/config.xml, jobs/dotnet_corefx_windows_stress_unittests/config.xml, jobs/dotnet_llilc/config.xml, jobs/dotnet_llilc_debug_win64/config.xml, jobs/dotnet_llilc_release_win64/config.xml, jobs/dotnet_wcf_outerloop/config.xml
* Add unittest stress config
* Avoid copying .ni.dll for Linux builds.  mscorlib.ni.dll is the windows cross-genned version and causes problems.
* llilc change scripting to python
=> Various config updates

jobs/dotnet_coreclr_windows_debug/config.xml, jobs/dotnet_coreclr_windows_debug_prtest/config.xml, jobs/dotnet_coreclr_windows_release/config.xml, jobs/dotnet_coreclr_windows_release_prtest/config.xml
Once https://github.com/dotnet/coreclr/pull/1116
gets merged, start building FreeBSD mscorlib as well.
=> Build FreeBSD mscorlib on Windows

ci-nodes/management/clean-workspaces.groovy
Walks the nodes and if idle, takes each offline, cleans the workspace root and then brings the node back online.
=> Add script to clean workspaces

tools/parameterize-job.groovy
Script can be copied into the script console in Jenkins and used to modify existing PR jobs so that they.
Do not use for push trigger jobs since this appears to currently break the push trigger (the push trigger doesn't replace variables with defaults while comparing the repo URL against the push notification).
=> Initial script used to parameterize a job

ci-nodes/management/Capture-Image.ps1, ci-nodes/management/Cycle-Nodes.ps1, ci-nodes/management/check-is-idle.groovy
Auto reimage allows the system to automatically take machines in the pool offline for updates, rather than having to manually determine when machines are ready
=> Enable auto-reimage

ci-nodes/management/clean-workspaces.groovy
Should avoid changing offline nodes, improve logging, etc.  This script now runs every few hours to periodically clean the disks
=> Fix the workspace cleaner

jobs/generation/Utilities.groovy
String.join doesn't appear to resolve when running netci.groovy in the CI system, though it does locally.  Just avoid it for now.
=> Fix odd missing method with String.join

jobs/generation/Utilities.groovy
Default behavior is the same, but a non-default version may be applied.  This allows for implementation of the auto-image version update
=> Add versioned machine affinities

jobs/generation/Utilities.groovy
This will allow for transition to the auto images without having to special case each OS with a version.  It will be removed once the transition is complete.
=> Add a generic version for auto or latest

jobs/generation/Utilities.groovy
The perf issue has been reported in https://issues.jenkins-ci.org/browse/JENKINS-32371
=> Use days to keep vs. num to keep to improve logRotator performance.

jobs/data/repolist.txt, jobs/generation/MetaGenerator.groovy, jobs/generation/Utilities.groovy
This change makes multi-branch support possible in Jenkins.  It extends the list of of configuration properties for a repo to a branch name.  If a branch name is specified, a branch specific folder is generated underneath the repo name.  GithubBranchName is passed to netci.groovy while generating, and should be used when setting up jobs (Utilities.standardJobSetup, addStandardParameters)
=> Initial multi-branch support

jobs/generation/Utilities.groovy
=> Move the test label to Ubuntu 14.04.

jobs/generation/Utilities.groovy
Avoids cases where we get a 'notbuilt' badge or odd cases where we are missing artifacts
=> Avoid skipping builds for non-PR if netci is changed.

jobs/generation/Utilities.groovy
Windows 2016 has support for Docker Containers.
cc: @mmitche
=> Add Windows 2016 machine type

jobs/generation/Utilities.groovy
- "Windows 2016" should have an underscore to match Windows_NT
- Update the image to the latest version
cc: @mmitche
=> Update setMachineAffinity for Windows 2016

jobs/generation/Utilities.groovy
cc @mmitche @joshfree 
This image is currently on my local box, since azure Nano server image doesn't have many of the required featured turned on. The other option is to use a custom vhd and upload to azure. Looking into doing it, but using this local vm now for testing purposes.
=> Add nano server image to jenkins jobs.

jobs/generation/Utilities.groovy
On private PRs triggers, permitted orgs and users should be admins, so they may request for others.
fyi @jashook
=> Fix private PR triggers

jobs/generation/Utilities.groovy
Adds 'latest-or-auto-temp' version that corresponds to 'windows || <dynamic image version'.  Will be used during rollout of the Windows dynamic scaling
Add temp label for elevated
=> Add new label that corresponds to windows machines and auto machines

jobs/data/repolist.txt, jobs/generation/MetaGenerator.groovy
Relies on an incoming parameter(ServerName) to the meta generator:  By default the server name is set to 'dotnet-ci'. If specified server name does not match the parameter, then the repo is skipped.
Add the server name to all the tracked repos
=> Add multi-server capabilities

jobs/generation/Utilities.groovy
In order to avoid building more than just the target branch, flow runs need to have a workspace
/cc @Priya91
=> Add automatic workspace requirement for flow jobs

jobs/generation/Utilities.groovy
Corresponds to new image that includes the rootfs for building
=> Add a label for the arm32/arm64 cross builds

jobs/generation/RootGenerator.groovy, jobs/scripts/disable_jobs_in_folder.groovy, jobs/scripts/system_cleaner.groovy, jobs/scripts/workspace_cleaner.groovy
Builds up the basic jobs for dotnet-ci instances.  To use, create a new freestyle job with source control pointing to dotnet-ci and process job DSLs in the jobs/generation/RootGenerator.groovy script file, then run.  Job should be set to run on pushes to dotnet-ci
=> Root generator

jobs/generation/Utilities.groovy
Use with Utilities.setMachineAffinity(job, 'Windows_NT', 'latest-dev15')
/cc @davkean @smile21prc @otawfik-ms
=> Add a dev15 image to the win2012 r2 list

jobs/data/repolist.txt, jobs/generation/MetaGenerator.groovy
This change allows for multiple groovy files to be used. They can also target different servers if desired.  This is motivated by some teams' desires to move CI definitions into subdirectories, as well as a desire to have a separate perf server.  We can put the perf definitions in another file which runs on the other server.
@dilijev This should allow you to move your CI definition if you like too
=> Allow for multiple DSL definitions

jobs/generation/Utilities.groovy
The commit changes the arm32 auto vm to use the most up to date vm with
the simulator mounted at /opt/
=> arm32 correctly setup on VM.

jobs/generation/JobReport.groovy, jobs/generation/Utilities.groovy
To avoid unnecessary runs, we use an SCM poll as the cron trigger, unless alwaysRun = true (new last parameter of addPeriodicTrigger)
=> Use SCM polling for cron triggers

jobs/generation/MetaGenerator.groovy
Under newer versions of the job-dsl-plugin, the ghprb trigger startup appears to be getting the older value of the github project property rather than the newest one written (the generator sets it twice).  This causes us to start triggers improperly for the ci test projects.  Work around this by instead just setting the URL and then the github project property.
=> Workaround issue in job-dsl-plugin

jobs/scripts/workspace_cleaner.groovy
Limit robocopy retries to 2, to avoid looping forever (default is 1,000,000)
Fixes #311
=> Limit robocopy retries

jobs/generation/Utilities.groovy
This adds zip and unzip to the fedora images, which some infrastructure in CoreCLR needs.
=> Bump Fedora Image

jobs/generation/Utilities.groovy
FYI. @mmitche, @jasonmalinowski, @dotnet/roslyn-infrastructure
=> Updating the 'latest-or-auto-internal' label to use the VS2015.3 image.

jobs/data/repolist.txt
After discussion with @zhenlan, we we no longer want 1.0.0-rc2 as a branch to test. 
Removing this from repolist.txt to prevent branch generation
=> Remove rc2 from dotnet/wcf branches to test

jobs/generation/Utilities.groovy
We're planning on adding a couple of extra jobs to the corefx CI, running on kernel version 4.6.x. This adds a couple of mappings for images that I have created.
@Priya91 @mmitche
=> Add Linux 4.6.x image mappings to Utilities.setMachineAffinity

jobs/data/repolist.txt, jobs/generation/MetaGenerator.groovy
Today most PR triggers are branch specific.  They only apply to the current branch.  This isn't great in cases where we are working on dev branches.  In these cases, we'd just like to use the PR definitions from another branch.  This commit, combined with forthcoming Github Pull Request Builder, begins to address this.  There are two primary features:
* Adding the ability to mark a branch as the "default" PR branch.
* Adding the ability to mark a branch definition as the PR definition for other branches (usually not mentioned in the repo list)
These properties control two build parameters:
GithubPRTargetBranches - Comma separated list of branches targeted by the CI definition which should be targeted for PRs
GithubPRSkipBranches - Comma separated list of branches targeted by the CI …
=> Allow for more fine grained control over PR branch triggers

jobs/generation/Utilities.groovy
=> Update Utilities.groovy to have an internal machine affinity label that does not include the static pool.

jobs/generation/Utilities.groovy
There has been some drift between image IDs and the labels (which should match except for variations on setup scripts, e.g. outer vs. regular).  Fix up the image labels.  Goes along with changes to the Jenkins configuration.
/cc @Priya91 @ellismg
=> Bring labels into line with image IDs

jobs/generation/Utilities.groovy
We're going to be bringing up support for openSUSE 42.1 (among other distros). I've created an image which should be suitable to use; this adds the Utilities.groovy mappings for it.
@mmitche , @ellismg
=> Add openSUSE 42.1 mappings

jobs/generation/Utilities.groovy
This change uses a captured vm with an 11gb ext4 filesystem for the arm
emulator runs in place of the 7gb it had before.
=> Increase the storage for the emulator fs

jobs/generation/Utilities.groovy
This adds a helper function which maps from an OS name ("Windows_NT", "Fedora24", etc) to a temporary "publish RID", which can be used to control which RID our init-tools script publishes for. It is intended to make bootstrapping the CI system for our repos easier.
Usage would be as follows, in coreclr for example:
Currently:
coreclr/netci.groovy
```groovy
case 'Ubuntu':
...
{
buildCommands += "./build.sh verbose ${lowerConfiguration} ${arch}"
}
```
New:
```groovy
case 'Ubuntu':
case 'Ubuntu16.10':
...
else
{
def bootstrapRid = Utilities.getBoostrapPublishRid(os)
def bootstrapRidEnv = bootstrapRid != null ? '__PUBLISH_RID=${bootstrapRid} ' : ''
buildCommands += "${bootstrapRidEnv}./build.sh verbose ${lowerConfiguration} ${arch}"
}
```
The `Ubuntu` build command will be the same, but …
=> Add getBoostrapPublishRid function

jobs/generation/Utilities.groovy
Everywhere else, this string is capitalized.
=> Fix capitalization mistake in boostrap RID map

jobs/data/repolist.txt
The dev branch will be deleted soon, and dotnet-docker-nightly only
needs CI for the master branch at this point.
cc: @mmitche @MichaelSimons
=> Remove dev branch of dotnet-docker-nightly

jobs/data/repolist.txt
cc: @mmitche 
Adding 1.1.0 release branch of corefx to the CI system
=> Adding release/1.1.0 corefx branch to CI

jobs/generation/MetaGenerator.groovy, jobs/generation/PostGen.groovy, jobs/generation/PreGen.groovy
Run two additional groovy scripts.  PreGen.groovy goes before the netci.groovy execution, while PostGen.groovy goes after.  Since each groovy execution within the same DSL step shares the same state, Pre and Post gen can affect/be affected by the netci.grooy execution.
=> Add pre and post generation

jobs/generation/Utilities.groovy
FYI: @mmitche, @jaredpar, @jasonmalinowski, @Pilchie 
This image will support the Open Integration Framework Tests: https://github.com/dotnet/roslyn/pull/13732
We can move it to be post preview 4 whenever we are ready to make the switch for Roslyn as a whole.
=> Update Utilities.groovy to include a machine affinity entry for VS15 Preview 4.

jobs/data/repolist.txt
This adds the dev branch `ws-trust` to the CI system as we bring a new feature online
=> Add wcf/ws-trust branch to CI

jobs/data/repolist.txt
Doing this on my fork first for testing and will change this over to
dotnet once I have it in good shape.
=> Add corefx perf runs to dotnet-ci2

jobs/generation/Utilities.groovy
=> Update Utilities.groovy to use the AzureRM template labels for the VS15.P5 nodes.

jobs/generation/Utilities.groovy
=> Update Utilities.groovy to use a WinServer 2016 based image for VS15.P5

jobs/generation/Utilities.groovy
corefx's netci.groovy expects these names to be of a particular format. Instead of special-casing this, or changing all the rest, I've just made these names the same as the other OS's.
@mmitche
=> Change Fedora 24 names to match other names

jobs/generation/Utilities.groovy
FYI. @mmitche, @dotnet/roslyn-infrastructure, @jasonmalinowski
=> Updating Utilities.groovy to no longer include the static pool of machines in the `latest-or-auto-internal` group.

jobs/generation/Utilities.groovy
Some projects use commit depth during CI.  Shallow clone breaks this
=> Disable shallow clone as this breaks CI for some scenarios

jobs/generation/Utilities.groovy
To use, add the following at the bottom of the job definition file:
// Runs the CROSS check by default
Utilities.addCROSSCheck(this, project, branch)
// Runs the CROSS check only when '@dotnet-bot test cross please' is commented
Utilities.addCROSSCheck(this, project, branch, false /*runByDefault*/)
=> Add cross check integration to Utilities.

jobs/generation/Utilities.groovy
Currently, the help message displays a wall of content in tabular form.
This change transforms:
> The following is a list of valid commands on this PR.  To invoke a command, comment the indicated phrase on
the PR
> **The following commands are valid for all PRs and repositories.**
>
> Comment Phrase | Action
>-------------- | ------
>@dotnet-bot test this please | Re-run all legs.  Use sparingly
>@dotnet-bot test ci please | Generates (but does not run) jobs based on changes to the groovy job definitions in this branch
> @dotnet-bot help | Print this help message
to:
> The following is a list of valid commands on this PR.  To invoke a command, comment the indicated phrase on
the PR
>**The following commands are valid for all PRs and repositories.**
>
><details>
>  <summary>Click to …
=> Emit collapsed tables on `@dotnet-bot help`

jobs/generation/Utilities.groovy
There seems to be an issue with RC3 image for some where the VsSdk.targets is not found.
Adding a legacy RC2 image, so that it can be used explicitly until the issue is resolved with RC3 images.
=> Add entries for rc2 images

jobs/data/repolist.txt
Moving sdk from private to public generation. Dependent on a similar change in the internal version, and https://github.com/dotnet/sdk/pull/737.
=> Added sdk builds

jobs/generation/Utilities.groovy
For "Only AMD64 and I386 are supported"
=> Add flaky CMAKE failure to auto-retry list

jobs/generation/Utilities.groovy
This will hopefully allow everybody who's *allowed* to trigger ARM64 to get it automatically on their own PRs.
(Sorry, I couldn't resist also fixing 1: other method comments and 2: the triple-T typo in permitAllSubmittters)
=> Add a way to default-trigger private jobs

jobs/data/repolist.txt
Add the perf.groovy defined in the citest repo to turn on our stabilty
runs for the perf lab.
=> Add CITest Stability

jobs/data/repolist.txt
We are moving the stability tests over to perf-infra and off of citest.
So I need to remove the entry we had for citest and add the entry for
perf-infra.
=> Move stability testing to perf-infra

jobs/data/repolist.txt
There seems to be some issue with updating commit statuses from server 2,
=> Move mono/linker to instance 1

jobs/generation/Utilities.groovy
Tizen will use the same image with 'arm-cross-latest'
Related issue : https://github.com/dotnet/core-setup/pull/1512
=> [ARM/CI] Add Tizen os to machine map

jobs/generation/Utilities.groovy
Rework labels to no longer refer to 'mac'
=> Add OSX 10.12

jobs/data/repolist.txt
=> Rename roslyn-project-system -> project-system

jobs/generation/MetaGenerator.groovy
This PR creates a view in the root folder of each project, giving a full view of the health of the project. It includes all non-pr builds (determined by regex for everything not ending in `prtest`). It also includes job build and run statistics, test statistics, and test trends. For an example of what this will look like, see https://ci.dot.net/job/dotnet_roslyn/view/Official%20Builds/, where I've manually created a view that looks like what we'll see after merge. I've tested the view configuration on a private Jenkins server, so it should compile and run correctly. Provided we're satisfied with this view, I'll port it over to the internal repo as well. Tagging @mmitche @tannergooding @jaredpar @dotnet/roslyn-infrastructure.
=> Official build view

jobs/scripts/workspace_cleaner.groovy
This is not particularly critical, but this update fixes two bugs:
* If a target machine were to be deleted during cleanup, we'd hit an exception and exit. Instead, keep going.
* Use find with '*' -delete to delete on Unix, to avoid bash argument expansion issues in directories with large numbers of files
=> Update workspace cleaner

jobs/data/repolist.txt
This branch has a substantially reduced number of jobs because we just
want to validate the workflow in representative cases.
=> Add coreclr:dev/unix_test_workflow branch to CI

jobs/generation/MetaGenerator.groovy, jobs/generation/Utilities.groovy
This factors out view creation so that it can be used by other scripts, and moves view creation such that every public folder created by the metagenerator gets a view. Tagging @mmitche FYI @dotnet/roslyn-infrastructure.
=> Factors out the view creation

jobs/generation/Utilities.groovy
Allow restriction of generation to non-dtap.  No machines are currently labeled DTAP.
=> Allow restriction to non-DTAP machines

jobs/generation/Utilities.groovy, management/nodes/Capture-VM.ps1, management/nodes/Images.csv, management/nodes/startupScripts/fedora24-20170420-outer.sh, management/nodes/startupScripts/fedora24-20170420.sh
@mmitche 
Fedora 24 wasn't in the "ValidateSet" for Capture-VM.ps1, so I added it.
=> Update Fedora 24 images. Includes the "requests" python module.

jobs/data/repolist.txt
This feature branch has a `netci.groovy` that should be running a substantially reduced set of jobs to avoid stressing the CI: https://github.com/dotnet/coreclr/compare/dev/local-gc . cc @Maoni0 @sergiy-k @adityamandaleeka . @mmitche is this OK?
=> Add CoreCLR branch dev/local-gc to CI

jobs/data/repolist.txt
This turns on performance runs for both CoreFX and CoreCLR on the
release/2.0.0 branches.
=> Add release/2.0.0 branch to perf runs

vars/waitForHelixRuns.groovy
Avoid NPE when there is no status content available.
Also add some debugging asserts
=> Add asserts and avoid NPE

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/rhel72-20170525.sh
This will use the new images for RHEL inner loop jobs.  I will follow up with a PR to update the outerloop images tomorrow.
I've already added clouds to both ci and ci2 with the new labels, so things should just work, but if something goes sideways, please revert this commit.
=> Bump RHEL images to pick up LLVM with PGO fix

jobs/generation/Utilities.groovy
Remove Nano Exclusion (now just covered by Helix)
Disable Win10, which is a non-functional 2016 TP5 image
=> Update image list

jobs/generation/Utilities.groovy
Always retry on NuGet cache corruptions to reduce its impact. until it's
root caused and fixed.
=> Always retry on NuGet cache corruptions to reduce its impact

jobs/data/repolist.txt
This reverts commit bd42888661fed0dbf6ea83f6fe1400aca068ada2. This branch is in the process of being decommissioned.
=> Revert "Add CoreCLR branch dev/local-gc to CI (#663)"

jobs/data/repolist.txt
@andygerlicher @jeffkl @cdmihai, this should light up CI for the 15.3 stabilization branch
=> Add MSBuild vs15.3 branch

vars/waitForHelixRuns.groovy
https://ci3.dot.net/job/dotnet_corefx/job/master/job/portable-windows-Config_Debug+OuterLoop_false_prtest/921/console had an instance were the Helix api hadn't registered the correlation id initially but responded in subsequent calls. This change adds a wait so that even if an exception is thrown initially, we allow retry to happen till failure.
here was the exception thrown.
```
[Pipeline] echo
java.lang.NullPointerException
[Pipeline] echo
null
[Pipeline] echo
[Ljava.lang.StackTraceElement;@45c3620e
[Pipeline] httpRequest
HttpMethod: GET
```
=> Wait for initial response from Helix API

src/org/dotnet/ci/pipelines/Pipeline.groovy, src/org/dotnet/ci/pipelines/scm/GithubPipelineScm.groovy
This sets the GitHub cloning to use an auth token.  The token is just a simple R/O public repo token (no selected scopes), but serves the identify the cloner.  This is useful to avoid rate limiting issues that might be propping up because of pipelines
=> Clone repo using an auth token

src/jobs/generation/JobReport.groovy, src/org/dotnet/ci/pipelines/Pipeline.groovy, src/org/dotnet/ci/triggers/GenericTriggerBuilder.groovy, tests/dsl/pipeline_manual_trigger.groovy
Adds the ability to create a pipeline that is only manually triggered.  This isn't so much a trigger as just a way of creating the job.  Jobs are created on the trigger call, so this allows for a job that isn't triggered from outside of a manual action.
=> Add a manual trigger option

tests/pipeline/pipeline-tests.groovy, vars/waitForHelixRuns.groovy
The waitForHelixRuns function was ignoring work item failures when there are no analyses.
=> Fix waitForHelixRuns ignoring work item failures

jobs/data/repolist.txt
We need to keep 15.0 for servicing - rest can be removed.
=> Disable CI for stale Roslyn and PS branches

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/win2012-20170809-elevated.ps1, management/nodes/startupScripts/win2012-20170810.ps1
Custom script extensions were updated from 1.8->1.9, which caused problems with these two images.
Running C:\Packages\..\resetState.cmd in the custom script extension that refuses to run the script (in this case 1.8) and then recapturing fixes the issue.
=> Update images that had non-functioning custom script extensions

src/jobs/generation/MetaGenerator.groovy, src/jobs/generation/RootGenerator.groovy
Propagate the sdk implementation branch from the root generator forward and use as the default utilities branch (rather than master)
=> Set a default utilities branch

tests/pipeline/pipeline-tests.groovy, vars/getUserEmail.groovy
When uploading perf results to benchview, we want to supply the email
address of the user who initiated the run. Return the github email
address if accessible, and if not, return <username>@github.login, so
that we don't collide with potential actual @github.com email addresses.
=> Add getUserEmail function

src/jobs/generation/MetaGenerator.groovy, src/jobs/generation/RootGenerator.groovy, src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/pipelines/scm/GithubPipelineScm.groovy, src/org/dotnet/ci/pipelines/scm/VSTSPipelineScm.groovy
Use scoped for PRs to work around issues with newer gits being much much slower checking out repos with large numbers of refs.
https://github.com/dotnet/core-eng/issues/1700
=> Use scoped refspecs

jobs/generation/MetaGenerator.groovy, jobs/generation/RootGenerator.groovy, jobs/generation/Utilities.groovy
Use scoped refspec for PRs to work around a performance issue with newer git implementations, especially on Windows
=> Use scoped refspec

vars/getUserEmail.groovy
There is a chance that the Mailer property for a particular user will be
null when a user manually starts a job. In that case, return
userId@github.login.
=> Fix getUserEmail

tests/pipeline/pipeline-tests.groovy, vars/simpleNode.groovy
For non-vm machines, we want to be able to specify them by their label.
This change adds an overload to simpleNode that takes a single label as
argument. This change also converts the osName + version version of
simpleNode to use the new overload.
=> Add simpleNode function that takes a label

jobs/generation/Utilities.groovy, management/nodes/Create-VM.ps1, management/nodes/Images.csv, management/nodes/startupScripts/win2016-20170921.ps1
Introducing a new image Docker 17.06.1-ee-2, which supports multi-stage builds. To prepare this image I did the following -
1. Create VM using win2016-20161018-1
2. Remove Containers feature using `Uninstall-WindowsFeature Containers` PowerShell command
3. Install Docker EE as described at https://store.docker.com/editions/enterprise/docker-ee-server-windows
4. Sysprep and deploy using the instructions at https://github.com/dotnet/core-eng/blob/master/Documentation/Jenkins/Adding-New-Jenkins-VM.md
@mmitche please suggest how do I switch CI from `win2016-20161018-1` to `win2016-20170921` and validate if this new image works at all?
@MichaelSimons PTAL
@karajas FYI.
=> New image with Docker 17.06.1-ee-2.

jobs/generation/Utilities.groovy
* Standard win2012 image now has VS2017
* Standard non-outer linux images now have clang3.9
=> Switch default images

src/org/dotnet/ci/pipelines/Pipeline.groovy, src/org/dotnet/helix/HelixEvent.groovy, src/org/dotnet/helix/HelixEventData.groovy, src/org/dotnet/helix/HelixEventSender.groovy, src/org/dotnet/helix/HelixTraceListener.groovy, src/org/dotnet/helix/IHelixEventSender.groovy, src/org/dotnet/helix/NoopSender.groovy, vars/createSender.groovy, vars/createSenderMap.groovy, vars/generateRandomUUID.groovy, vars/getBuildNumber.groovy, vars/getSenderMap.groovy, vars/sendEvent.groovy, vars/simpleDockerNode.groovy
- Update Pipeline.groovy to support `getValidJobNameString` as a static method so that we can later derive the job name.  I made a separate change which made this irrelevant where I explicitly specify a job name rather than letting it derive.  The result is that being able to determine the job name via a static method is not necessary.  I left this change in my PR, but I'm ok with reverting it if it's a concern.
- Update Pipeline.groovy to allow you to explicitly specify job names when creating triggers
- Add Helix event logic so that we can send Helix events.  I added the Helix event logic here (rather than BuildTools) so that we can send events from anywhere during the pipeline
- Update simpleDockerNode so that we can pass arguments to the docker command
=> Add helix event sending, support docker args in simpleDockerNode, misc other utils

jobs/data/repolist.txt
Tagging @mmitche. Branch no longer exists on the project system and was merged a while ago.
=> Remove repotoolset-exp job from project system.

src/jobs/generation/Utilities.groovy, vars/simpleDockerNode.groovy, vars/simpleNode.groovy
This avoids async cleanup, which is a problem with the Helix agents plugin (since nodes don't get cleaned before reassignment)
=> Use explicit patterns when cleaning

data/repolist.txt
The V# branch `vs2017-rtm` was retired in favor of `dev15.5` and `dev15.6`.
=> Update F# CI branches

scripts/remove_offline_nodes.groovy
This works around a current bug that sometimes leaves an agent in Jenkins without being cleaned up if deletion from azure fails.  This bug is fixed in a currently unreleased Azure VM Agents version.
=> Add script that removes offline azure nodes not taken manually offline

data/repolist.txt
Enable CI for Microsoft/dotnet-framework-docker.
Refer to https://github.com/Microsoft/dotnet-framework-docker/issues/66
=> Include .NET framework Docker repo

data/repolist.txt
The dev15.5 branch is no longer needed and 15.7 was just added.
=> update F# branch definitions

vars/waitForHelixRuns.groovy
Per @mmitche this should fix our issue with a lack of timestamps in Jenkins Helix runs
=> Move timestamps {} closure into helixRunTasks

data/repolist.txt
Add 15.6 (current lock down) and 15.7 (product construction lock down for Core 2.1).
=> Update MSBuild branches (15.6, 15.7)

data/repolist.txt
=> Adding the release/2.1.3xx branches for cli-migrate and clicommandlineparser

data/repolist.txt
Include `dotnet/dotnet-buildtools-prereqs-docker` repo.
Refer to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/issues/2
=> Add dotnet-buildtools-prereqs-docker

data/repolist.txt
Fix typo in repository name `dotnet-buildtools-prereqs-docker`.
Refer to https://github.com/dotnet/dotnet-buildtools-prereqs-docker/pull/4
=> Fix repository name

data/repolist.txt
Removing dev15.7-preview1 from repolist since dev15.7-preview1 is already shipped.
=> Removing dev15.7-preview1 from repolist

src/jobs/generation/Utilities.groovy, tests/pipeline/pipeline-tests.groovy
Useful for Helix queues, which don't have versions in the agents map.  To avoid conflicting overrides, remove optional parameter to the original setMachineAffinity.
Add a test for new Helix Windows.10.Amd64.ClientRS3.DevEx.Open queue
=> Allow an explicit label name for setMachineAffinity

management/nodes/Images.csv
Docker would not start reliably on this image.  Based on log output and some searching, it appears this should be fixed by a kernel update.  This image has been updated to the latest kernel and deployed.
=> Fixes ubuntu1404-20170120 image allocation issues

management/nodes/Images.csv, management/nodes/startupScripts/ubuntu1404-20170925.sh, management/nodes/startupScripts/ubuntu1404-20180321.sh, src/org/dotnet/ci/util/Agents.groovy
Also add startup script for ubuntu1404-20170925 since it looks like it got missed.  Verified that the CoreCLR PR that requires lldb-3.6 builds on this and building CoreFX now to make sure lldb-3.9 doesn't conflict.
=> Add ubuntu1404-20180321 with lldb-3.6 for CoreCLR.

tests/pipeline/pipeline-tests.groovy, vars/waitForHelixRuns.groovy
If multiple correlation ids submit to the same queue, we won't track all of them because we key the tasks and results off of queue id.  Instead, generate a unique key in the map by utilizing the property bad as well as the correlation id as a last resort.
=> Use more descriptive/unique keys in task and results map

scripts/remove_offline_nodes.groovy, src/jobs/generation/RootGenerator.groovy
Sometimes Jenkins takes agents offline for no apparent reasnon.  We remove these agents periodically.  Add Helix agents to the list of agents to remove
=> Remove Helix agents in node cleanup script

data/repolist.txt
TestFx [1.2.1](https://github.com/Microsoft/testfx/tree/1.2.1)
Vstest [15.7](https://github.com/Microsoft/vstest/tree/rel/15.7)
=> Add RTM branches for testfx, & vstest in dotnet-ci

data/repolist.txt
Adding dotnet-apiport/service branch for dotnet-bot to build because we are doing new dev work on that branch.
=> Add dotnet-apiport/service branch for build

vars/waitForHelixRuns.groovy
Most of the time the message is empty and it looks like a NPE to the user.
=> Make initial work item lookup catch messages a little more descriptive

data/repolist.txt
https://github.com/dotnet/source-build/blob/dev/release/2.1.0-preview2-fsharp/netci.groovy
This `dev/release/2.1.0-preview2-fsharp` branch is a fork from `release/2.1.0-preview2` made to work on an F# fix with the ability to run full CI. We'll be adding commits to `release/2.1.0-preview2` that work around the issue.
=> Add source-build dev/release/2.1.0-preview2-fsharp branch

data/repolist.txt
Microsoft/visualfsharp just added a `dev16.0` branch to track future work.
@mmitche for review.
=> enable CI on fsharp/dev16.0

data/repolist.txt
One possible reason for our Jenkins instability is the large number of
branches that are currently being tracked. The branches in Roslyn are
particularly problematic due to the number of tests they run. Trimming
out some branches that are not under active use anymore.
=> Trim Roslyn branches

data/repolist.txt
`master`, `dev15.9`, and `dev16.0` have been converted to VSTS CI.
`dev15.6` is no longer a branch and is not being serviced.
`dev15.7` is active for potential servicing fixes and `dev15.8` is active for preview builds so those are being left on Jenkins.
@mmitche for review/merge.
=> remove F# branches that have been converted to VSTS CI

vars/simpleDockerNode.groovy
If this is not done, then once we exit the docker container, the hidden dirs will be owned by root and will not be deletable by the Jenkins process
=> Enable deletion of hidden files

data/repolist.txt
PR validation has been moved to [Azure DevOps](https://dev.azure.com/dnceng/public/_build?definitionId=216).
=> remove roslyn-tools from jenkins

data/repolist.txt
Part of aspnet/EntityFrameworkCore#14053
(Keeping 2.1.x and 2.2.x branches for now since we haven't migrated them yet.)
cc @mmitche @dagood @ajcvickers
=> Remove aspnet/EntityFrameworkCore master branch

data/repolist.txt
feature/utf8string doesn't exist in corefx anymore.
cc: @danmosemsft @stephentoub @mmitche
=> Remove corefx ci entries for branches that don't use Jenkins CI

data/repolist.txt
We've migrated this repo to use Azure DevOps pipelines instead.
=> Remove docker-tools repo from CI repo list

data/repolist.txt
Looks like dotnet/standard is now using Azure DevOps for ci.
@wtgodbe, please confirm it's ok to cleanup the Jenkins master job for Standard
=> Remove dotnet/standard entry

data/repolist.txt
We've added Azure DevOps ci into corefxlab.
cc: @ahsonkhan @chcosta @mmitche
=> Remove corefxlab ci trigger

data/repolist.txt
It looks like dotnet/metadata-tools is already on Azure DevOps.  @tmat , can you confirm it's ok to remove this from Jenkins?
FYI @mmitche
=> Remove metadata-tools
