dotnet/dotnet-ci

ci-nodes/management/Capture-Image.ps1, ci-nodes/management/Cycle-Nodes.ps1, ci-nodes/startup/jenkins-windows-startup.ps1
Add script to capture an image
Update the window startup bootstrap script
Add additional logging to Cycle-Nodes
=> Various updates

ci-nodes/management/Cycle-Nodes.ps1
Was not marking nodes as cycled, so nodes got cycled multiple times before the whole set
converged
=> Fix a bug in Cycle-Nodes

jobs/generation/Utilities.groovy
* Modify the job name creator to have a folder option
* Add utilities to get the project name and org name given fully qualified project name
=> Add some utilities

ci-nodes/management/Capture-Image.ps1, ci-nodes/management/Cycle-Nodes.ps1, ci-nodes/management/inventory.txt
* Update inventory to latest images and counts
* Modify inventory to have cloud service parameter
* Add dotnet-ci-nodes2 cloud service (hit VM instance limit in dotnet-ci-nodes)
* Update imaging scripts to deal with multiple cloud services
=> VM inventory and imaging update

ci-nodes/management/Cycle-Nodes.ps1, ci-nodes/management/inventory.txt
Tweak some scripting in Cycle-Nodes to improve the logging and also add 5 additional linux machines.
=> Add linux nodes and tweak Cycle-Nodes

README.md, docs/CI-SETUP.md, docs/WORKFLOWS.md, docs/WRITING-NETCI.md
* Developer workflow info
* More info on writing netci files
=> Add more docs

jobs/generation/Utilities.groovy
Added a few new APIs that unify PR and non PR modes.  Add API for determining the node labels.  Added some documentation.
=> White space change and cleanup

jobs/data/repolist.txt
Adding corefxlab to the repolist.txt to start on issue https://github.com/dotnet/corefxlab/issues/371 
/cc @mmitche @KrzysztofCwalina
=> Adding corefxlab to the repolist.txt

jobs/generation/Utilities.groovy
* 90 days for jobs themselves
* 21 days for artifacts
* Maximum 50 builds of artifacts
=> Increase retention rates for job data

jobs/data/repolist.txt
Adding Microsoft/PartsUnlimited to the repo list.
=> Adding PartsUnlimited to repo list.

jobs/generation/Utilities.groovy
We want to get runs on Ubuntu 15.10 and RHEL 7 for CoreFX and CoreCLR, this is in preparation for that.
=> Add Ubuntu 15.10 and RHEL7 to affinity list

jobs/generation/Utilities.groovy
=> Add Ubuntu test machine label for new image.

jobs/generation/Utilities.groovy
Update to a new image that can actually be spun up by the Azure plugin
in Jenkins.
=> Update RHEL7.2 Image

jobs/data/repolist.txt
=> Add specific branch for F#

jobs/data/repolist.txt
=> Add branches vs2015 and coreclr to Microsoft/visualfsharp

jobs/data/repolist.txt
Also remove unneeded buildtools branch
=> Branchify wcf to master

jobs/data/repolist.txt
=> Added roslyn branch to Microsoft/visualfsharp tracking

docs/END-USER-TASKS.md
=> Add end-user task document

jobs/generation/Utilities.groovy
cc @mmitche @joshfree 
For dotnet/corefx#6526
=> Add outerloop images to Linux OSes.

jobs/generation/Utilities.groovy
=> Update Utilities.groovy to use `githubPullRequest` instead of `pullRequest`

jobs/generation/MetaGenerator.groovy
To avoid generating jobs so often, use polling with an ignore extension, ensuring that generators only get run when there is a change to relevant sources
=> Use polling with ignore

docs/SYSTEM-OVERVIEW.md
fyi @smile21prc @stephentoub @KKK9527 @Priya91
=> Add basics of system overview doc

jobs/data/repolist.txt
=> Set Chakra to use the branch structure

tools/Local-Job-Gen.ps1
Standalone execution doesn't work with extensions (yet? ever?)  To work around this, replace the githubPullRequest extension with the deprecated pullRequest and remove whitelistTargetBranches for now.
=> Workaround a few issues with the job dsl standalone execution

jobs/data/repolist.txt
=> Add llilc repo to CI control

jobs/generation/Utilities.groovy
The windows image to have a newer version of the Azure custom script extension.  The 1.7 version was not properly running
=> Update windows image

jobs/data/repolist.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dotnet/dotnet-ci/238)
=> Add Microsoft/ChakraCore branch release/1.2 to repolist.txt

jobs/generation/Utilities.groovy, tools/Local-Job-Gen.ps1
This change introduces job generation reports into the Utility functionality.  By adding JobReport.Report.generateJobReport() to the end of the groovy file, the following things are generated:
1) 3 CSV files, one for push triggered jobs, one for PR jobs, and one for cron jobs.
2) Additional information about unreferenced jobs (jobs with no triggers).  Jobs that are triggered via build flows and other means can use JobReport.Report.addJobReference(job name) to mark a job as referenced.
This also fixes up Local-Job-Gen with a few more workarounds
=> Job Generation Reports

jobs/generation/Utilities.groovy
=> Revert "Make freebsd dynamic"

jobs/generation/Utilities.groovy
cc @joshfree @ellismg @mmitche
=> Add Ubuntu16.04 support.

tools/Local-Job-Gen.ps1
* Needed to correctly replace the internal utils
* Needed to remove package lines
* Needed to add job reportm functionality to the file
=> Fix the local gen

jobs/data/repolist.txt
FYI @digitalinfinity
---
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dotnet/dotnet-ci/271)
=> Add ChakraCore branch linux to CI.

jobs/generation/Utilities.groovy
Allows callers to customize the default value for these parameters.
=> Customize GitBranchOrCommit and GitRefSpec defaults

jobs/generation/Utilities.groovy
=> Revert "Customize GitBranchOrCommit and GitRefSpec defaults"

jobs/generation/Utilities.groovy
This change allows callers to customize the default values for GitBranchOrCommit and GitRefSpec.
The previous attempt at this change modified the signatures of existing methods in place and subtly changed the defaults.  This approach defines new methods and has the existing ones feed into those.  It also use a more declarative model that should be more resilient to changes.
Verified that locally generated PR jobs still have '${sha1}' as the push value.
=> Customize defaults for GitBranchOrCommit and GitRefSpec

jobs/generation/Utilities.groovy
This is actually listed in the doc comment but not an actual parameter to the function.  I did a search on the dotnet org and found no active uses of this function hence it should not be a breaking change.
=> addPrivateGithubPRTrigger needs triggerPhaseOnly option

jobs/data/repolist.txt
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dotnet/dotnet-ci/278)
=> Add CI dev branches for ChakraCore.

jobs/generation/Utilities.groovy
=> Add Debian8.4

jobs/generation/Utilities.groovy
cc @mmitche @ellismg @joshfree  Can someone please merge.. Thanks!
=> Add outerloop label for Debian8.4

jobs/generation/Utilities.groovy
cc @mmitche @joshfree 
In reference to issue dotnet/corefx#7939
=> Update windows nano server labels to pick the latest version.

jobs/data/repolist.txt
=> Add dotnet/core-setup repo

jobs/generation/Utilities.groovy
=> Add 2016 to Windows Nano name.

jobs/generation/Utilities.groovy, tools/Local-Job-Gen.ps1
=> New archival opts

jobs/generation/Utilities.groovy
Adds a webhook to each job for build events (start/finish) for metric gathering
/cc @jaredpar @smile21prc
=> Add webhooks to jobs

jobs/data/repolist.txt
=> Add more core-setup and cli branches

jobs/generation/Utilities.groovy, tools/Local-Job-Gen.ps1
* Overload for getFullJobName which specifies no project (which is not used)
* Make local job gen work properly with newer files
=> Various fixes

jobs/generation/Utilities.groovy
=> Arm32 auto image update.

jobs/generation/Utilities.groovy
=> Add elevated mac boxes for running outerloop runs.

jobs/data/repolist.txt
/cc @ellismg @mmitche @weshaggard
=> Add dotnet/buildtools release/1.0.0 to CI

jobs/data/repolist.txt
@weshaggard @mmitche 
Don't know how to validate this.
=> Add corefx dev/api support to CI

jobs/data/repolist.txt
=> Enable CI on corefx dev/cms_unix

jobs/data/repolist.txt
=> New cli branch

jobs/generation/Utilities.groovy
=> Add parameter that allows for differentiating CLI telemtry in CI

jobs/generation/Utilities.groovy
FYI. @mmitche, @jasonmalinowski, @jaredpar, @dotnet/roslyn-infrastructure
=> Adding an image label for VS2015.3

jobs/data/repolist.txt
=> Add corefx release/1.0.1 branch

tools/Local-Job-Gen.ps1
=> Semi-colons are not required

jobs/generation/ArchivalSettings.groovy, jobs/generation/JobReport.groovy, jobs/generation/MetaGenerator.groovy, jobs/generation/RootGenerator.groovy, jobs/generation/Utilities.groovy
This change is [<img src="https://reviewable.io/review_button.svg" height="35" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/dotnet/dotnet-ci/360)
=> Fix mixed tabs and trailing whitespace.

jobs/generation/Utilities.groovy
FYI. @mmitche, @jasonmalinowski, @jaredpar, @brettfo
=> Adding the 'Win2012.R2 + VS2013.5 + VS2015.3 + VS15.P3' image.

jobs/data/repolist.txt
Adding our new preview branch, and trimming down some older branches that aren't used anymore.
*Review:* @dotnet/roslyn-infrastructure
=> Update Roslyn branch list

jobs/generation/TriggerBuilder.groovy, jobs/generation/Utilities.groovy, tools/Local-Job-Gen.ps1
This adds a trigger builder class to the set of Utilities, making it clearer how triggers are set up and managed.
=> New trigger builder

jobs/generation/Utilities.groovy
Having trouble with the array addition implementations (flatten isn't working).  Will need to experiment a bit.
=> Temporarily revert to old PR builder impl

jobs/generation/SummaryBuilder.groovy, tools/Local-Job-Gen.ps1
This allows for additions of sets of links on the build finished page
=> Adds a summary builder

jobs/generation/Utilities.groovy
=> Revert "Enable queue position updates"

jobs/generation/Utilities.groovy
=> Revert "Revert "Enable queue position updates""

jobs/data/repolist.txt
=> add new cli branch

jobs/generation/Utilities.groovy
This mostly just copies the existing archival functions and their options.
=> Add Azure artifact archival functions, for use with the Azure Storage Jenkins plugin.

jobs/data/repolist.txt
@dotnet/roslyn-infrastructure  @mmitche Who has access to merge this?
=> Add roslyn dev15-preview-4-dogfood branch

jobs/data/repolist.txt
=> Use shorter branch name to avoid MAX_PATH

jobs/generation/Utilities.groovy
=> Add latest-or-auto-perf

jobs/generation/Utilities.groovy
=> Adds internal Ubuntu image

jobs/data/repolist.txt
=> Add dotnet-docker-nightly to repolist

jobs/generation/Utilities.groovy
This should resolve msbuild node reuse issues
=> Move to update 3 by default

tools/Local-Job-Gen.ps1
Implement additional workaround to fix errors in Local-Job-Gen.ps1
=> Fix Local-Job-Gen.ps1

jobs/generation/Utilities.groovy
=> Update Utilities.groovy with Ubuntu 16.10 and openSUSE 42.1 image names

jobs/generation/RootGenerator.groovy, jobs/scripts/generator_cleaner.groovy
Use source control for generator_cleaner
=> Remove disabling of jobs until we know it works

jobs/generation/Utilities.groovy
This utility, when called at the end of a groovy file, will add a job to the branch which prints a help message when '@dotnet-bot help' is commented in the PR.
This PR should not be merged without corresponding changes to the GHPRB plugin deployed.
=> Implement a help job

jobs/generation/Utilities.groovy
Pipes need to be escaped in the help table
=> Escape pipes

jobs/generation/Utilities.groovy
The latest included docker and testing showed it's good to go
=> Roll 1604 forward to latest

jobs/data/repolist.txt
@joperezr @mmitche PTAL
We should merge it once https://github.com/dotnet/coreclr/pull/7084 is merged.
=> Enable CoreCLR release/1.1.0 branch for CI

jobs/data/repolist.txt
=> Adding the templating change to CI.

jobs/data/repolist.txt
Now tested through tests in dotnet-ci repo
=> Remove refined-help

jobs/data/repolist.txt
=> Enable CI for Core-Setup release/1.1.0

jobs/scripts/system_cleaner.groovy
Delete everything under GenPRTest in addition to just disabled items
=> System cleaner update

jobs/scripts/system_cleaner.groovy
The safety breaks keep us from accidentally deleting too many items
=> Reenable the system cleaner with safety breaks enabled

jobs/data/repolist.txt
* Need to add CI coverage for the new branch WCF 1.1.0
=> Add CI Coverage for WCF 1.1.0

jobs/data/repolist.txt
=> Add dotnet-docker to repolist

docs/CI-SETUP.md
=> Update docs to reflect GitHub update

jobs/generation/Utilities.groovy
I've made a new version of the image because we needed a higher ulimit.
=> Update openSUSE 42.1 label

jobs/generation/Utilities.groovy
I needed to update the max inotify instances in the VM.
@mmitche
=> Update Ubuntu 16.10 image label

jobs/generation/Utilities.groovy
=> Adding an internal image for VS15.P5

jobs/generation/Utilities.groovy
=> Update centos to disable transparent huge pages

jobs/data/repolist.txt
=> Add dotnet/versions to repolist

jobs/data/repolist.txt
I am adding my fork to the repo list for testing.  Once this is done I
will delete it.
=> Add my fork of CoreCLR to repolist

jobs/data/repolist.txt
=> Add dotnet-apiport

jobs/generation/TriggerBuilder.groovy, jobs/generation/Utilities.groovy
Retries the following phrases
* 'channel is already closed',
* 'Connection aborted',
* 'Cannot delete workspace',
* 'failed to mkdirs'
Retries a maximum of 3 times at 15 seconds apart.
=> Job auto retry

jobs/data/repolist.txt
Also fixed some spelling / missing terms in comments
=> Add Microsoft/TypeScript

jobs/generation/Utilities.groovy
=> Add the hardfp rootfs

jobs/generation/Utilities.groovy
Add clone timeout to list of retry strings
=> Add new ubuntu image (nodejs, nvm, npm)

jobs/generation/Utilities.groovy
=> Add Fedora 24 image mappings

jobs/generation/MetaGenerator.groovy, jobs/generation/RootGenerator.groovy
Extension compatible with newer versions of DSL
=> Use relativeTargetDirectory instead of relativeTargetDirectory

management/nodes/Images.csv, management/nodes/startupScripts/ubuntu1404-20161019.sh
=> Add correct arm image

jobs/data/repolist.txt
Could you please review this Matt? 
@mmitche
=> adding dotnet/core to Jenkins repository list

jobs/data/repolist.txt
Add the `dotnet/netcorecli-fsc` repo to CI
=> Add dotnet/netcorecli-fsc repo to CI list

jobs/generation/Utilities.groovy
=> Adding an entry for the Dev15.RC image.

jobs/data/repolist.txt
This is our preview3 branch.
@mmitche @piotrpMSFT
=> Adding dotnet/cli branch=rel/1.0.0-preview3 to CI

jobs/data/repolist.txt
Tagging @dotnet/roslyn-infrastructure @mmitche for review. /cc @dotnet/project-system.
=> Added the dev15-rc project system branch.

jobs/generation/Utilities.groovy
Notifications are non-concatenating, so set all at once.
=> Fix webhooks

jobs/data/repolist.txt
@jasonmalinowski @dotnet/roslyn-infrastructure
=> Add Roslyn dev15-rc2 branch to repolist

jobs/data/repolist.txt
=> Add corefx:dev/apple_crypto to repolist

jobs/generation/GenerationSettings.groovy, jobs/generation/MetaGenerator.groovy, jobs/generation/PreGen.groovy, jobs/generation/RootGenerator.groovy, jobs/generation/Utilities.groovy
Master is becoming the primary implementation branch
=> Merge master-i2 into master

jobs/generation/Utilities.groovy
=> Updating the Dev15 RC image to win2016-20161121

jobs/data/repolist.txt
=> Add ci for mono linker project

jobs/data/repolist.txt
Add new branches of `dotnet/netcorecli-fsc`
- `rel/1.0.0-preview2`
- `rel/1.0.0-preview2.1`
=> add branch preview2, preview2.1 of dotnet/netcorecli-fsc

jobs/generation/MetaGenerator.groovy
Attempts to fix the issues with thread counts.  Hopefully temporary.
=> Reduce thread load by limit generator concurrency

jobs/data/repolist.txt
Tagging @dotnet/roslyn-infrastructure @mmitche for review.
=> Updated the project system branches to master and dev15-rc2

jobs/generation/MetaGenerator.groovy
=> Revert "Reduce thread load by limit generator concurrency"

jobs/data/repolist.txt
=> Add the CLI preview4 branch to CI

jobs/generation/Utilities.groovy
=> Updating the Dev15 RC images to RC2.

jobs/generation/Utilities.groovy
TP5 appears be seeing lots of restarts now.
=> Disable TP5 nano jobs

jobs/data/repolist.txt
/cc @mmitche @mellinoe @ellismg @weshaggard
=> Enable CI for core-setup/dev/eng

jobs/generation/Utilities.groovy
=> Bias retention in favor of PR logs

jobs/data/repolist.txt
=> Add dotnet/cli master branch

jobs/data/repolist.txt
=> Add rc3 CLI branch to CI

jobs/data/repolist.txt
Added rc3 for the project system, and moved dotnet/sdk definitions to public since the repo is public. Tagging @mmitche for review.
=> Rc3 Branches

jobs/data/repolist.txt
=> Removed sdk until we update the scripts to not use internal utils.

jobs/data/repolist.txt
=> Added post-dev15 for project system

jobs/generation/Utilities.groovy
@mmitche ptal
/cc @wateret @RussKeldorph
=> Update arm32 emulator image

jobs/data/repolist.txt
=> Revert "Added sdk builds"

jobs/data/repolist.txt
Reverts dotnet/dotnet-ci#583. Dependent PR is merged.
=> Revert "Revert "Added sdk builds""

jobs/data/repolist.txt
Tagging @dotnet/roslyn-infrastructure
=> Update dev15 branches

jobs/data/repolist.txt
=> Add symreader-converter repo

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/deb84-20170214-outer.sh, management/nodes/startupScripts/deb84-20170214.sh
@mmitche This adds a newer Debian 8.4 image. I have several more of these coming soon.
=> Add new Debian 8.4 image

jobs/data/repolist.txt
=> Add dotnet/standard to CI repo list

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/ubuntu1604-20170215.sh
/cc @dilijev 
This adds the required clang package.  Will merge tomorrow morning.
=> Add clang 3.8 dev package

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/ubuntu1604-20170215.sh
Reverts dotnet/dotnet-ci#597
Something is wrong with the allocation of these VMs.  Need to test it first.
=> Revert "Add clang 3.8 dev package"

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/centos71-20170216-outer.sh, management/nodes/startupScripts/centos71-20170216.sh
@mmitche Please take a look. I've already "Validate"'d the new images in ci.dot.net/configure, so everything should be good to go once this is merged.
=> Update Utilities.groovy to use newer CentOS 7.1 image

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/suse421-20170216-outer.sh, management/nodes/startupScripts/suse421-20170216.sh
=> Update Utilities.groovy to use newer openSUSE 42.1 image.

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/ubuntu1604-20170216-outer-outer.sh, management/nodes/startupScripts/ubuntu1604-20170216-outer.sh, management/nodes/startupScripts/ubuntu1610-20170216-outer.sh, management/nodes/startupScripts/ubuntu1610-20170216.sh
=> Add new Ubuntu 16.04 and Ubuntu 16.10 images

jobs/data/repolist.txt
/cc @eerhardt @livarcocc @mmitche
=> add cli rel/1.0.1 branch

jobs/data/repolist.txt
=> Add more branches to perf test

jobs/data/repolist.txt
@mmitche
/cc @jianchun @leirocks
=> Add ChakraCore branch release/2.0 to repolist,txt

jobs/data/repolist.txt
=> Updated roslyn project system branches for post-rtm

jobs/data/repolist.txt
=> Updated sdk for post rtm

jobs/data/repolist.txt
=> Enable CI on the dotnet-docker-nightly sdk-1.0.0 branch

jobs/data/repolist.txt
=> Remove post-dev15

jobs/data/repolist.txt
=> add CliCommandLineParser to repo list

jobs/data/repolist.txt
=> Moved ProjFileTools public

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/win2016-20170307-internal.ps1, management/nodes/startupScripts/win2016-20170307.ps1
FYI. @mmitche, @jasonmalinowski, @dotnet/roslyn-infrastructure
=> Adding the VS15.0 image

jobs/data/repolist.txt
=> Added dev15.2.x to ci requests

jobs/data/repolist.txt
=> Add xliff-tasks to CI.

jobs/data/repolist.txt
@jaredpar - I don't have permissions to merge directly.
FYI @KevinRansom
=> enable CI for additional F# branch

jobs/data/repolist.txt
@mmitche @dotnet/roslyn-infrastructure
=> The future branch no longer exists on the sdk.

jobs/data/repolist.txt
=> Adding cli-migrate repo to CI

jobs/generation/MetaGenerator.groovy
@mmitche addressed feedback from initial implementation.
=> Official build view

jobs/generation/Utilities.groovy
@mmitche, FYI @dotnet/roslyn-infrastructure @jaredpar @tannergooding.
=> Moved all documentation to javadoc format

jobs/generation/Utilities.groovy
=> Fixed job list property

jobs/data/repolist.txt
FYI to @dotnet/roslyn-infrastructure
=> Add dotnet/roslyn features/editorconfig-in-compiler to branch list

jobs/data/repolist.txt
/cc @srivatsn @davkean @333fred @dotnet/project-system
=> Add dev15.3.x branch for project-system

jobs/data/repolist.txt
=> Adding SDK rel/1.0.0 to jenkins

jobs/generation/Utilities.groovy
Hope to add huge pages in the future.
@mmitche ptal
=> Add arm64_ubuntu tag reference

jobs/data/repolist.txt
=> Add release/2.0.0 branches to CI

jobs/data/repolist.txt
=> Add release/2.0.0 branches for SDK and CLI

jobs/data/repolist.txt
- Delete the 'run' branch
- Sort
=> Cleanup branches

management/nodes/Clean-Resource-Group.ps1
Current version of Azure storage plugin may not be cleaning up Failed deployments in some cases.  Clean these.
=> Clean failed deployments

jobs/data/repolist.txt
cc @mslaguana @louislaf @digitalinfinity
=> Remove unused ChakraCore branches from CI

jobs/data/repolist.txt
=> Add Roslyn features/ins topic branch to Jenkins

jobs/generation/Utilities.groovy, management/nodes/Images.csv
* Add 15.3 image for project system
=> Add new images

jobs/generation/Utilities.groovy
This is part of the first proof of concept that we are doing to enable a Repro Environment functionality when a job fails.
cc: @mmitche @alexperovich
=> Add new parameter ReproBuild to all jobs

jobs/generation/Utilities.groovy
=> Changing echo message for addReproBuild

jobs/data/repolist.txt
=> Adding rel/1.1.0 branches for CLI and SDK

jobs/data/repolist.txt
=> repolist.txt: Add ChakraCore branches release/{1.5, 1.5-ci, 1.6, 1.6-ci}

jobs/generation/Utilities.groovy
=> Reprobuild - Add curl command to snapshot

jobs/data/repolist.txt
=> Remove project-system's dev15.1.x branch

jobs/generation/Utilities.groovy
This is just to unblock until elevation issue on 20170531 is fixed
=> Revert to 20170303-elevated

jobs/generation/Utilities.groovy, management/nodes/Images.csv
=> Adding .NET 4.6.2 SDK to win2012 images

vars/addSummaryLink.groovy, vars/waitForHelixRuns.groovy
=> Allow Job Status page to carry link instead of the PR Status Details

jobs/data/repolist.txt
=> Enable CI for features/non-trailing

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/win2016-20170613-internal.ps1, management/nodes/startupScripts/win2016-20170613.ps1
FYI. @mmitche, @jasonmalinowski
=> Adding the 'Win2016 + VS2017.3 Preview 2' image

vars/waitForHelixRuns.groovy
=> Check workitem status, add more verbose logging and handle exceptions more gracefully

README.md
Add a link in doc to the mirror repo in VSTS
=> Add a link in doc to the mirror repo in VSTS

README.md
=> Edit the doc

tests/pipeline/pipeline-tests.groovy, vars/getUser.groovy
Also add a default for non-manually launched runs (dotnet-bot)
=> Implement getUser for manually launched runs

jobs/data/repolist.txt
=> Add release/2.0.0-preview2 branches of CLI and SDK

data/repolist.txt, management/nodes/Deploy-Image.ps1, management/nodes/Images.csv, management/nodes/startupScripts/ubuntu1404-20160211-1-internal.sh, management/nodes/startupScripts/ubuntu1404-20160211-1.sh, management/nodes/startupScripts/win2008-20170303.ps1, management/nodes/startupScripts/win2012-20170303.ps1, management/nodes/startupScripts/win2012-20170531-elevated.ps1, management/nodes/startupScripts/win2012-20170531.ps1, management/nodes/startupScripts/win2016-20170531-internal.ps1, management/nodes/startupScripts/win2016-20170531.ps1, management/nodes/startupScripts/win2016-20170613-internal.ps1, management/nodes/startupScripts/win2016-20170613.ps1, src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/util/Agents.groovy
=> Update from master

docs/CI-PIPELINES.md, docs/sample-declaration.groovy
Adds documentation detailing onboarding new pipelines and a guide on how to write pipelines.
=> Add documentation for pipelines

jobs/data/repolist.txt
cc @jasonmalinowski @dotnet/roslyn-infrastructure FYI
=> Remove entries for deleted dev15.6 branches

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/win2016-20170712.ps1, management/nodes/startupScripts/win2016-20170717-internal.ps1, management/nodes/startupScripts/win2016-20170717.ps1
Still need to finish distributing to storage accounts prior to merging.
=> Add preview 4 and update preview 0 with OS updates to prevent VM crashes

data/repolist.txt
Add CI for release/uwp6.0 branches of coreclr and corefx (#733)
* Add CI for release/uwp6.0 branches of coreclr and corefx
* Add CI for wcf and core-setup release/uwp6.0 branches
* Add ability to run helix test infra for corefx release/uwp6.0
=> Cherry-pick 0f589555ba782baab5effd2b05df203edf4a16d6 from master

jobs/generation/Utilities.groovy, management/nodes/Images.csv
=> Update ubuntu 16.04 images and update latest-or-auto

jobs/generation/Utilities.groovy
FYI. @mmitche, @agocke, @jasonmalinowski
=> Adding 'latest-dev15-3-preview6' to the Utilities.groovy image list.

jobs/generation/Utilities.groovy, management/nodes/Images.csv, management/nodes/startupScripts/win2016-201700802-internal.ps1, management/nodes/startupScripts/win2016-20170731-internal.ps1, management/nodes/startupScripts/win2016-20170731.ps1, management/nodes/startupScripts/win2016-20170802.ps1
=> Adding the Dev15.3 Preview 7 images.

data/repolist.txt
=> Add sbomer/coreclr for testing pipeline scripts

data/repolist.txt
=> add my dev pipeline

jobs/generation/MetaGenerator.groovy
This allows the use of the option useFilteredGenerationTriggers=false to use github/vsts push triggers rather than polling with filtered paths.  This works around https://github.com/dotnet/core-eng/issues/1531
=> Allow disabling of generation filters

scripts/workspace_cleaner.groovy
Regardless of whether they were taken temporarily offline.
=> Wipe all nodes

jobs/scripts/workspace_cleaner.groovy
Regardless of whether they were taken temporarily offline.
=> Wipe all nodes (#778)

data/repolist.txt
=> Add Corefx/master to ci4

data/repolist.txt
The job we need is not in ci3 but ci :|
=> corefx jobs from ci

jobs/generation/Utilities.groovy
FreeBSD should be added back with a version suffix on the same.
=> Remove EOL'd OS's

tests/pipeline/pipeline-tests.groovy, vars/checkoutRepo.groovy
Checkout utility function with automatic retry
=> Add checkout with retry

jobs/generation/Utilities.groovy
=> Merge repro functionality from dev/pipeline to master

jobs/generation/Utilities.groovy
Fixes https://github.com/dotnet/core-eng/issues/1621.
=> Retry on no space on device

jobs/data/repolist.txt
=> Add dotnet-cli-archiver to CI

jobs/generation/Utilities.groovy
@sunandabalu and @alexperovich
=> Update Repro Tool API to the Prod instance

src/org/dotnet/ci/pipelines/Pipeline.groovy
=> Revert "Remove credentials for public clone"

jobs/data/repolist.txt
Sorry for splitting these, our branching strategy has been a bit fuzzy.
=> Add source-build dev/release/2.0.0 branch.

jobs/data/repolist.txt
Add my perf ci test branch so I can more easily test changes to
perf.groovy
=> Add nategraf perf ci test branch

jobs/data/repolist.txt
=> Adding new branches for CLI/SDK for 15.5

jobs/data/repolist.txt
=> Add CI for CLI 2.0.x infrastructure branch

src/jobs/generation/MetaGenerator.groovy, src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/pipelines/Pipeline.groovy, src/org/dotnet/ci/pipelines/scm/VSTSPipelineScm.groovy, src/org/dotnet/ci/triggers/VSTSTriggerBuilder.groovy
Implement VSTS PR trigger support in dev/pipelinesupport branch of dotnet-ci
=> Implement VSTS PR trigger support in dev/pipelinesupport branch of dotnet-ci

src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/triggers/VSTSTriggerBuilder.groovy
=> Import both triggers classes

src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/triggers/VSTSTriggerBuilder.groovy
Fix trigger name and remove redundant import
=> Fix trigger name and remove redundant import

src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/triggers/VSTSTriggerBuilder.groovy
=> Fix trigger usage.

src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/triggers/VSTSTriggerBuilder.groovy
Remove redundant field in VSTS triggers.
=> Remove redundant field in VSTS triggers.

src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/triggers/VSTSTriggerBuilder.groovy
=> Fix null param

jobs/data/repolist.txt
https://github.com/dotnet/buildtools/blob/release/1.1.0/netci.groovy
https://github.com/dotnet/buildtools/blob/release/2.0.0/netci.groovy
/cc @eerhardt
=> Add BuildTools 1.1.0 and 2.0.0 branches

src/org/dotnet/ci/pipelines/scm/VSTSPipelineScm.groovy
=> Fix params

src/org/dotnet/ci/pipelines/scm/VSTSPipelineScm.groovy
=> fix merge conflict

src/org/dotnet/ci/pipelines/scm/VSTSPipelineScm.groovy
=> Fix pileline scm groovy file

src/jobs/generation/MetaGenerator.groovy
Fix generation for non-DSL PR tests
=> Fix generation for non-DSL PR tests

docs/CI-SETUP.md
Add doc on onboarding private repo
=> Add doc on onboarding private repo

vars/waitForHelixRuns.groovy
Attempt to address dotnet/core-eng#1808
=> Be explicit about waitUntil return value

data/repolist.txt
@dotnet/dotnet-cli @nguerrera @mmitche
=> Add dotnet/core-sdk and dotnet/toolset to CI

data/repolist.txt
For CLI, core-sdk and toolset repos. Adding a new branch where the repo refactoring work will happen. Also, adding dev/release/2.0 for the CLI, for when we rename that branch.
@mmitche @dotnet/dotnet-cli @nguerrera
=> Adding new branches to CI for CLI, core-sdk and toolset

management/nodes/Images.csv, management/nodes/startupScripts/win2016-20171014.ps1, src/org/dotnet/ci/util/Agents.groovy
These changes are similar to (https://github.com/dotnet/dotnet-ci/pull/820) with an additional step where DNS Server role is enabled. I verified `Invoke-WebRequest` cmdlet works correctly in a Docker container running Nano Server.
=> Windows Server 2016 with Docker 17.06.2-ee-3

data/repolist.txt
@mmitche Can you look at this PR?
=> Adding dotnet-apiport dev branch to build

data/repolist.txt
@mmitche @nguerrera @tannergooding
=> Adding dev/release/2.0 branch of SDK to CI

data/repolist.txt
@dotnet/roslyn-infrastructure for review. Thanks
=> Enable CI for features/compiler branch

data/repolist.txt
=> Add corefx release/2.0.0 to list for pipelines

data/repolist.txt
=> repolist: Add ChakraCore release/1.8

data/repolist.txt
=> Adding release/2.1 for the CLI

data/repolist.txt
=> Putting the right release/2.1 branch on CI

data/repolist.txt
@dotnet/roslyn-infrastructure please review
=> Add  dotnet/project-system branch=dev15.6-preview2

data/repolist.txt
FYI. @mmitche, @livarcocc 
Removes the temporary branches used for testing the repo-toolset changes and adds the new release/2.1 branch
=> Updating the repolist for SDK

src/jobs/generation/Utilities.groovy, src/org/dotnet/ci/pipelines/scm/GithubPipelineScm.groovy
https://github.com/dotnet/core-eng/issues/2262
=> update Branch Name policy

data/repolist.txt
I just created a [features/async-streams](https://github.com/dotnet/roslyn/tree/features/async-streams) branch in roslyn repo. Adding it to CI following [instructions](https://github.com/dotnet/roslyn/blob/master/docs/infrastructure/feature%20branches%20jenkins.md). 
Tagging @jaredpar, @mmitche, @jasonmalinowski to merge. Thanks
=> Add features/async-streams branch

docs/CI-CLASSIC.md, docs/sample-classic-declaration.groovy, management/nodes/Clean-Resource-Group.ps1, src/jobs/generation/MetaGenerator.groovy, src/jobs/generation/RootGenerator.groovy, src/jobs/generation/Utilities.groovy, tests/dsl/simple_job_check_out_to_subdir.groovy, tests/dsl/simple_traditional_job.groovy, tests/dsl/test_repro_job.groovy
The addStandardParameters isn't the normal entrypoint for adding parameters.  It's not even used any longer.
Also change some other places where */ was showing up
=> Move */ -> refs/heads/ translation.

data/repolist.txt
CC @jaredpar, @mmitche, @jasonmalinowski
=> Add dotnet/roslyn/features/constraints branch to jenkins

data/repolist.txt
=> Added features/dataflow

data/repolist.txt
release/2.1.1xx
release/2.1.2xx
release/2.1.3xx
@mmitche @tannergooding
=> Adding new branches for the CLI

vars/waitForHelixRuns.groovy
@mmitche  actually please review this one
=> Update waitForHelixRuns.groovy (upstream)

vars/waitForHelixRuns.groovy
=> Revert "Update waitForHelixRuns.groovy (upstream)"

data/repolist.txt
- Add [15.6 release branch](https://github.com/Microsoft/vstest/tree/rel/15.6) for Microsoft/vstest
=> Add branch rel/15.6 for vstest

data/repolist.txt
=> Add core release/2.1 branches to ci

data/repolist.txt
features/tuple-equality
features/stackalloc-init
features/custom-fixed
features/localsinit
features/verification
features/fixed-buffers
=> Added new Roslyn feature branches to the repolist.txt

data/repolist.txt
https://github.com/dotnet/buildtools/blob/release/2.1/netci.groovy
=> Add BuildTools 2.1 branch

data/repolist.txt
Also, hopefully, this triggers the regeneration of our master folder which I had deleted hoping it would get rid of zombie jobs and regenerate itself but didn't ... :)
=> Remove experimental MSBuild branch

data/repolist.txt
Tagging @jaredpar, @mmitche, @jasonmalinowski per [instructions](https://github.com/dotnet/roslyn/blob/5aa8207c84f99bc764dc1208d285c414dac7e51d/docs/infrastructure/feature%20branches%20jenkins.md).
=> Add features/generic-attributes branch to CI

data/repolist.txt
Related to dotnet/dotnet-docker-nightly#525
=> Hook up dotnet-docker nightly branch to CI

data/repolist.txt
=> Adding WebSdk to the repolist

data/repolist.txt
Companion PR https://github.com/aspnet/aspnet-docker/pull/371
cc @mmitche
=> Add aspnet/aspnet-docker dev branch to repo list

data/repolist.txt
For work on https://github.com/dotnet/roslyn/pull/24649
=> Add feature branch to repolist.txt

data/repolist.txt
Added aspnet/aspnet-docker master branch
Also, but all aspnet repos into the same section
@dagood @mmitche
=> Add master branch of aspnet/aspnet-docker

data/repolist.txt
=> Remove project-system/15.5.x branch

data/repolist.txt
=> enable CI on fsharp/dev15.8

data/repolist.txt
Relates to https://github.com/dotnet/roslyn/pull/25562
Tagging @jaredpar
=> Add feature branch for "deconstruction on default" feature

data/repolist.txt
Add [perf-improvements branch](https://github.com/Microsoft/vstest/tree/perf-improvements) for Microsoft/vstest
=> Add branch perf-improvements for vstest

data/repolist.txt
This branch is for Cyrus's work on embedded regex parsing.
=> Adding features/embeddedRegex to CI

data/repolist.txt
Sorry, need one more.
This branch is for Cyrus's work on embedded json parsing (I initially thought he'd use the same branch for regex and json work).
=> Add branch for features/embeddedJson

data/repolist.txt
=> Add branch for `features/ref-partial` to CI

data/repolist.txt
Add CI support for https://github.com/dotnet/roslyn-analyzers/tree/features/dataflow
=> Add CI support for roslyn-analyzers branch "features/dataflow"

data/repolist.txt
=> add roslyn 15.8 branches

data/repolist.txt
=> Adding release/2.1.4xx branches to CLI and SDK

data/repolist.txt
=> Add roslyn ranges branch to tracked list

data/repolist.txt
https://github.com/dotnet/source-build/blob/release/2.1.0-preview2/netci.groovy
https://github.com/dotnet/source-build/issues/455
/cc @dseefeld
=> Add source-build 2.1.0-preview2 branch

data/repolist.txt
I'm deleting this branch, just cleaning up `repolist.txt`.
=> Remove source-build dev/release/2.1.0-preview2-fsharp

data/repolist.txt
This branch is where we will try to annotate roslyn codebase with nullability annotations.
FYI @cston
=> Add branch `features/NullableDogfood`

data/repolist.txt
=> Add feature branch `features/generic-attributes`

data/repolist.txt
Making dotnet/sourcelink repo public.
=> Add dotnet/sourcelink

data/repolist.txt
=> Add machinelearning repo

data/repolist.txt
https://github.com/dotnet/source-build/blob/release/2.1.0-rc1/netci.groovy
=> Add source-build release/2.1.0-rc1 servicing branch

data/repolist.txt
=> MSBuild 15.8 branch

data/repolist.txt
Tagging @mmitche @jasonmalinowski @jaredpar for review. Thanks
=> Add `features/compiler` branch

data/repolist.txt
https://github.com/aspnet/IISIntegration/pull/855
=> Add aspnet/IISIntegration to repolist

data/repolist.txt
=> Add machinelearning release branch to CI

data/repolist.txt
Add release/2.1, remove dev/release/* and release/2.0
=> Update versions for source-build.

data/repolist.txt
Updating repolist for 15.8 branches for Roslyn and Project System repos
=> Updating repolist for 15.8 branches

data/repolist.txt
=> Added null-operator-enhancements to roslyn

data/repolist.txt
=> Add release/2.2.1xx branches of CLI/SDK to CI

data/repolist.txt
Tagging @mmitche @jasonmalinowski @jaredpar for review. Thanks
=> Add feature branches for target-typed-new and caller-expression

data/repolist.txt
=> Adding master branches for toolset and core-sdk and release/2.1.401

data/repolist.txt
=> Add release/2.2 branches for aspnet repos

data/repolist.txt
@mmitche @chcosta @natemcmaster
=> Add release/2.2 branches for IISIntegration

data/repolist.txt
Tagging @mmitche @jasonmalinowski @jaredpar for review. Thanks
=> Add branch for "line continuation comments" (VB feature)

data/repolist.txt
Add coreclr, corefx, core-setup branch=feature/utf8string CI support
=> Add branch=feature/utf8string

data/repolist.txt
=> Add experimental-classic-projects dotnet/sdk branch

data/repolist.txt
=> Fix CI test builds for CoreFX and CoreClr feature/utf8string

data/repolist.txt
=> Add source-build release/2.2 branch CI

data/repolist.txt
=> Add dotnet/cli release/2.1.5xx to CI

data/repolist.txt
=> Add MSBuild 15.9 branch

data/repolist.txt
Add dotnet/buildtools release/2.2 CI
/cc @weshaggard @mmitche
=> Update repolist.txt: Add dotnet/buildtools release/2.2 CI

data/repolist.txt
=> Adding dotnet/sdk release/2.1.5xx to CI

src/jobs/generation/TriggerBuilder.groovy, src/jobs/generation/Utilities.groovy, tests/dsl/traditional_job_with_paren_in_name.groovy
=> Updating TriggerBuilder to escape the string used for the default trigger phrase

data/repolist.txt
cc: @mmitche @eerhardt @shauheen
=> Remove machinelearning from repolist

data/repolist.txt
📝 Please do not rebase/squash/rewrite this pull request during the merge.
=> Add 15.9-preview2 branches to CI

data/repolist.txt
=> add ci for roslyn/dev15.9-preview2

data/repolist.txt
=> Removing CLI/SDK repos/branches that have moved to YAML

data/repolist.txt
@mmitche 
This branch will match VS dev16.
=> Adding release/2.2.2xx branches to CLI and SDK

data/repolist.txt
We're getting enough coverage from AzDO now and are ready to shut off the Jenkins builds. It looks like this is the way to do that :).
cc @pranavkm @mmitche
=> Disable Jenkins builds for aspnet/SignalR

data/repolist.txt
@dotnet/dotnet-cli @chcosta @mmitche
=> Removing jenkins from CLI/master and adding new 2.1.6xx branches

data/repolist.txt
=> Removing Jenkins for core-sdk and toolset repos

data/repolist.txt
=> Adding release/2.1.502 to Jenkins

data/repolist.txt
We have moved to ADO.
@mmitche @rainersigwald
=> Removing microsoft/msbuild from jenkins.

data/repolist.txt
Would you be able to look at this PR? @mmitche
=> Remove dotnet-apiport from repolist

data/repolist.txt
@livarcocc , can you confirm that removing the MSBuild entry is ok?
@GrabYourPitchforks, can you confirm that removing the utf8string branches from Jenkins is ok?
=> Remove unused branches

data/repolist.txt
=> Remove repo-refactoring

data/repolist.txt
@tmat , please confirm this is reasonable.
=> Remove symreader symreader-portable entries

data/repolist.txt
@singhsarab, please confirm it's ok to remove this entry from dotnet-ci (disable Jenkins for vstest master).
=> Remove vstest entry

data/repolist.txt
=> Remove websdk and templating master jobs

data/repolist.txt
=> Adding release/2.1.6xx and release/2.2.2xx to dotnet/cli and dotnet/sdk

data/repolist.txt
@tommcdon, can you please ack that this is ok?
=> Remove diagnostics repo from Jenkins

data/repolist.txt
=> Add roslyn-analyzers 2.9.x branch

data/repolist.txt
Addresses https://github.com/dotnet/arcade/pull/2504
@mmitche , PTAL and merge after @rainersigwald 's ack
=> Remove unneeded MSBuild VS servicing branches

data/repolist.txt
@brettfo , please confirm it is ok to delete these jobs from Jenkins.
@mmitche , please merge after Brett's confirmation.
=> Remove VisualFSharp from Jenkins

data/repolist.txt
These builds have migrated off of Jenkins and onto AzDO.
=> Remove Docker related CI builds

data/repolist.txt
=> Remove ci2 perf jobs and ci1 buildpipline job

data/repolist.txt
=> Remove perf-infra

data/repolist.txt
This has been migrated to AzDO.
@chcosta - please merge
=> Remove dotnet-framework-docker from CI

data/repolist.txt
* Also removed a non-existant branch.
=> Remove Jenkins from WCF master.
